### ISSUE TITLE
Publish to cloud front

### ISSUE THREAD

**Issue by juunone** [ambientlight/amplify-cli-action#6] opened 2020-04-02 05:22 UTC
hi i really useful to this amplify github actions
i want to publish to cloud front , not S3
but `publish -c` is not invalid command or `publish --invalidateCloudFront --yes` too.
i want to feature request this argument
thanks!

**Comment by ambientlight** [comment] 2020-04-04 17:56
duplicate of #5, was just added in #7, please refer to https://github.com/ambientlight/amplify-cli-action/issues/5#issuecomment-609066007
Thanks!

**Closed by ambientlight** 2020-04-04 17:56 UTC
